nome = str(input('Digite seu nome completo: ')).title()
nome_lista = nome.split()
p_nome = len(nome_lista[0])
print(f'Olá, {nome}!\nEstarei mostrando o seu nome todo maiúsculo e minusculo, quantas letras ele tem no total e\nquantas letras tem o seu primeiro nome:')
print(f'O seu nome completo em minúsculo fica: {nome.upper()}')
print(f'O seu nome completo em minúsculo fica: {nome.lower()}')
print(f'O seu nome completo tem no total: {len(nome.replace(" ", ""))} letras.')
print(f'O seu primeiro nome {nome_lista[0]} tem: {len(nome_lista[0])} letras.')