valor =  input('Digite um algo: ')
print(f'o tipo primitivo desse valor é {type(valor)}')
print(f'so tem espaços? {valor.isspace()}')
print(f'é um numero? {valor.isnumeric()}')
print(f'é alfabetico? {valor.isalpha()}')
print(f'é alfanumerico? {valor.isalnum()}')
print(f'está em maiuscula? {valor.isupper()}')
print(f'está em minuscula? {valor.islower()}')
print(f'esta capitalizado? {valor.istitle()}')