nome = str(input('Digite seu nome completo: '))
nome = nome.title()
nome_maiusculo = nome.upper()
nome_minusculo = nome.lower()
qnt_letras = len(nome.replace(" ", ""))
nome_lista = nome.split()
p_nome = len(nome_lista[0])
print(f'Olá, {nome}!\nEstarei mostrando o seu nome todo maiúsculo e minusculo, quantas letras ele tem no total e\nquantas letras tem o seu primeiro nome:')
print(f'O seu nome completo em minúsculo fica: {nome_maiusculo}')
print(f'O seu nome completo em minúsculo fica: {nome_minusculo}')
print(f'O seu nome completo tem no total: {qnt_letras} letras.')
print(f'O seu primeiro nome {nome_lista[0]} tem: {p_nome} letras.')